### PR TITLE
Regenerate SDK

### PR DESCRIPTION
**Pull request by shreyav**

### CODE REVIEW

**Comment by shreyav** [comment]
* **#173** <a href="https://app.graphite.dev/github/pr/lightsparkdev/kotlin-sdk/173?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shreyav and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by zhenlu** [comment]
I think these's an issue with new enum values

**Comment by shreyav** [comment]
> I think these's an issue with new enum values

ya, can I just no op `RemoteSigningSubEventType.VLS_MESSAGE`?

**Review by zhenlu — APPROVED** [review]

**Comment by shreyav** [comment]
### Merge activity

* **Jun 22, 4:57 AM EDT**: @shreyav merged this pull request with [Graphite](https://app.graphite.dev/github/pr/lightsparkdev/kotlin-sdk/173).

**Pull request merged**
